# Site settings
title: Question2Answer documentation
url: http://docs.question2answer.org
baseurl: /
permalink: pretty
exclude: [vendor]

# Build settings
markdown: CommonMarkGhPages
highlighter: rouge

# Menu layout
nav:
  main:
    - name: Install
      path: /install/
      sub: install
    - name: Customize
      path: /themes/
      sub: customize
    - name: Plugins
      path: /plugins/
      sub: plugins
    - name: Code
      path: /code/external/
      sub: code
    - name: Contribute
      path: /contribute/
      sub: contribute
    - name: Add-Ons
      path: /addons/
      sub: addons

  second:
    - name: Services
      url: /services/
      class: main-nav-link-separate
    - name: Sites
      url: https://www.question2answer.org/sites.php
    - name: Q&A
      url: https://www.question2answer.org/qa/

  footer:
    - name: Contact devs
      url: https://www.question2answer.org/feedback.php
    - name: Version history
      url: /install/versions/
    - name: License details
      url: https://www.question2answer.org/license.php
    - name: Demo sandbox
      url: http://demo.question2answer.org/

  install:
    - name: Basic Install
      path: /install/
    - name: WordPress
      path: /install/wordpress/
    - name: Single Sign-On
      path: /install/single-sign-on/
    - name: Upgrading
      path: /install/upgrade/
    - name: Optimization
      path: /install/optimize/
    - name: Security
      path: /install/security/
    - name: .htaccess
      path: /install/htaccess/

  customize:
    - name: Create a theme
      path: /themes/
    - name: Translate Q2A
      path: /translate/

  plugins:
    - name: Overview
      path: /plugins/
    - name: Modules
      path: /plugins/modules/
    - name: Layers
      path: /plugins/layers/
    - name: Overrides
      path: /plugins/overrides/
    - name: Plugin Tutorial
      path: /plugins/tutorial/

  code:
    - name: External
      path: /code/external/
    - name: Functions
      path: /code/functions/
    - name: App Structure
      path: /code/structure/

  contribute:
    - name: Issues
      path: /contribute/
    - name: Coding Style
      path: /contribute/coding-style/
    - name: Unit tests
      path: /contribute/unit-tests/
    - name: Documentation
      path: /contribute/docs/

  addons:
    - name: Translations
      path: /addons/translations/
    - name: Themes
      path: /addons/themes/
    - name: Plugins
      path: /addons/plugins/
    - name: Clients
      path: /addons/clients/

